# Generated by Django 4.0.3 on 2022-04-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='ajeet',
        ),
    ]
