# Generated by Django 4.0.3 on 2022-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
