# Generated by Django 4.0.3 on 2022-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=True, max_length=3, primary_key=True, serialize=False),
        ),
    ]
